sudo: required
services:
  - docker

before_install:
  - docker build -t joshtbecker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true joshtbecker/react-test npm test

after_success:
  - docker build -t joshtbecker/multi-client ./client
  - docker build -t joshtbecker/multi-nginx ./nginx
  - docker build -t joshtbecker/multi-server ./server
  - docker build -t joshtbecker/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push the images built above to Docker Hub
  - docker push joshtbecker/multi-client
  - docker push joshtbecker/multi-nginx
  - docker push joshtbecker/multi-server
  - docker push joshtbecker/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-817775124142
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_acceess_key: $AWS_SECRET_KEY